jobs:
- job: BuildPkg

  pool: mac-mini

  steps:
  - script: |
      ./ci/common.sh
      ./ci/build_android_plugin.sh
      ./ci/build_windows_plugin.sh
      ./ci/build_mac_plugin.sh
      ./ci/build_webgl_plugin.sh
  - script: |
      cd tests
      ./build_unity.sh
      dg deploy TestProject/Build/Android.apk
  - task: PublishBuildArtifacts@1
    inputs:
        PathtoPublish: './Effekseer.unitypackage'
        ArtifactName: 'package'
        publishLocation: 'Container'
